# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ChainCircle' do
    pod 'AFNetworking', '~> 3.2.0'
    pod 'MJExtension', ‘>= 3.0.13'
    pod 'SDWebImage', '~> 4.3.3'
    pod 'SVProgressHUD', '~> 2.2.5'
    pod 'MJRefresh', '~> 3.1.15.3'
    pod 'Masonry', '~> 1.1.0'
    pod 'IQKeyboardManager', '~> 5.0.8'
    pod 'LBXScan/LBXNative','~> 2.3'
    pod 'LBXScan/UI','~> 2.3'
    pod 'LxFTPRequest', '~> 1.1.1'
    pod 'SDCycleScrollView', '~> 1.75'
    pod 'YYCache', '~> 1.0.4'
    pod 'SGPagingView', '~> 1.3.6'

    pod 'mob_sharesdk', '~> 4.1.1'
    pod 'MOBFoundation', '~> 3.1.2'
    pod 'mob_sharesdk/ShareSDKUI'
    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
    pod 'mob_sharesdk/ShareSDKExtension'


end
